mytestkey=This value is from LOCAL properties file

merchant.username=merchant_username
merchant.password=merchant_password
notification.Url=https://URL_to_your_notification_service/dajskldjakls123

trustly.Url=http://localhost:8084/payment/initiate